# Generated by Django 5.0.1 on 2024-01-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
