# Generated by Django 4.2.6 on 2024-01-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dummy',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
