# Generated by Django 4.2.6 on 2024-01-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_dummy_age_alter_dummy_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummy',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dummy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dummy',
            name='roll',
        ),
        migrations.AddField(
            model_name='dummy',
            name='message',
            field=models.TextField(default='asdkjas dkas dkaskd kas ', max_length=1000),
            preserve_default=False,
        ),
    ]
