# Generated by Django 4.2.6 on 2024-01-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_dummy_age_remove_dummy_name_remove_dummy_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
